### ISSUE TITLE
改ページ

### ISSUE THREAD

**Issue by tmaeda3** [AntennaHouse/pdf5-ml#101]
たとえば、次のマップファイルで、特定のtopicheadやtopicrefの前で改ページしたいのですが、属性設定などの方法で実現できないでしょうか？

    <chapter>
      <topicref href="aaa.dita" />
      <topichead>　　　　　　　　　←この前で改ページ
        <topicref href="bbb.dita"/>
        <topicref href="ccc.dita"/>
      </topichead>
      <topicref href="ddd.dita"/>　　←この前で改ページ
    </chapter>

**Comment by ToshihikoMakita** [comment]
現在はオーサリングによる属性セッティングではできませんが、2019年9月中に予定している次のバージョンリリース（developブランチ→master）で、できるように考えます．

    <topicref href="xxx.dita" outputclass="break-page"/>

みたいな感じで良いでしょうか？

**Comment by tmaeda3** [comment]
牧田様

お世話になります。PSSJの前田です。

はい。ご提案通りで結構です。
よろしくお願いします。

前田　保 maeda.tamotsu@jp.panasonic.com<mailto:maeda.tamotsu@jp.panasonic.com>
パナソニック システムソリューションズ ジャパン株式会社
パブリックシステム事業本部　システム開発本部　ネットワークソリューション部　ＳＩ２課　１係
〒224-8539 横浜市都筑区佐江戸町600番地 S-10ビル
ダイヤルイン：080-9946-5153　※2019/8より電話番号が変わりました

**Comment by ToshihikoMakita** [comment]
Page-break control by topicref/@outputclass has been implemented today.

    (Samples)
    <topicref href="a.xml" outputclass="break-page"/> 
    <topicref href="a.xml" outputclass="break-column"/>
    <topicref href="a.xml" outputclass="break-no"/>
    <topicref href="a.xml" outputclass="break-auto"/>

"break-page" inserts `break-before="page"` into the relevant fo:block. "break-column" inserts `break-before="column"` into the relevant fo:block. "break-no" inhibits any page-break. "break-auto" means no user-level break control (depends on stylesheet default)

All of above does not work at the start of frontmatter, chapter, backmatter because PDF5-ML plug-in stylesheet generates fo:page-sequence for these elements.

I attached simple test data.
[page-break.zip](https://github.com/AntennaHouse/pdf5-ml/files/3612895/page-break.zip)

Any suggestions are welcome.

**Comment by tmaeda3** [comment]
Perfect! Thanks a lot.
