### ISSUE TITLE
How can I remove bullets from the elements within the hazardstatement messagepanel?

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#124]
I'm customizing the hazardstatement output to match our current requirements. How can I remove the bullets from the output?

![messagepanel](https://user-images.githubusercontent.com/36418458/71853412-f9149e00-30a0-11ea-85eb-6a531bc4631b.png)

I'm unable to find where the MessagePanel part of the template is pulling in the list-item style.

I'm adding customization for the following files:
 dita2fo_hazardstatement_domain.xsl
 default_style.xml

Any suggestions?

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
> I'm unable to find where the MessagePanel part of the template is pulling in the list-item style.

This is because `messagepanel` is the specialization of `ul` element. To remove the bullet, you can add the following customization templates:

    <xsl:template match="*[contains(@class, ' hazard-d/messagepanel ')]" priority="5">
      <xsl:apply-templates/>
    </xsl:template>
   
    <xsl:template match="*[contains(@class,' hazard-d/typeofhazard ')] | *[contains(@class,' hazard-d/consequence ')] | *[contains(@class,' hazard-d/howtoavoid ')]" mode="MODE_GET_STYLE" as="xs:string*">
     <xsl:sequence select="'atsP'"/>
    </xsl:template>
  
    <xsl:template match="*[contains(@class,' hazard-d/typeofhazard ')] | *[contains(@class,' hazard-d/consequence ')] | *[contains(@class,' hazard-d/howtoavoid ')]" priority="5">
      <fo:block>
        <xsl:call-template name="getAttributeSetWithLang"/>
        <xsl:call-template name="ahf:getUnivAtts"/>
        <xsl:copy-of select="ahf:getFoStyleAndProperty(.)"/>
        <xsl:apply-templates/>
      </fo:block>
    </xsl:template>

[ The before result ]

![before](https://user-images.githubusercontent.com/1801890/71874024-1f4f4200-3164-11ea-8b27-746e9df6ddba.png)

[ The after result ]

![after](https://user-images.githubusercontent.com/1801890/71874036-28d8aa00-3164-11ea-9fac-6cb29426e017.png)

Please adust @priority based on your customization template location.

**Comment by steinbacher01** [comment]
Thank you for the explanation. This makes sense and will be very helpful moving forward. 

The customization templates you provided work great!

Thanks, 

Leroy
