### ISSUE TITLE
-Dauto.scale.down.to.fit=yes not working

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#127]
I have some images in my PDF output that are bleeding into the right margin. 

![ImageBleed](https://user-images.githubusercontent.com/36418458/72467269-30213880-37a0-11ea-8074-26e014e9aecd.png)

It looks like the -Dauto.scale.down.to.fit=yes is only applied when the image placement="break". 
Is this intentional? 

Is there a way to apply the -Dauto.scale.down.to.fit parameter to all images regardless of the placement attribute value?

Thanks, 

Leroy

**Comment by ToshihikoMakita** [comment]
Unfortunately your PDF snap shot is bit small to understand what is happened.

About the inline-images, I didn't apply `@content-width="scale-down-to-fit"` because it exists with text in line-area. Furthermore there are no requests from user to us to implement it. Also several users want to apply font-size relative size such as content-width="1.0em" unconditionally because it should be the size of preceding/following characters. In these situations, I realized that there are no needs or certainty to implement `-Dauto.scale.down.to.fit="yes"` to inline-images.

If your documents do needs it, could you provide me the sample DITA authoring (and image files)?

**Comment by steinbacher01** [comment]
Here's a zip with the topic and the output I'm currently getting. 

Thanks, 

Leroy

[t_CheckTheIntegrityOfTheDownloadedFiles.zip](https://github.com/AntennaHouse/pdf5-ml/files/4071704/t_CheckTheIntegrityOfTheDownloadedFiles.zip)

**Comment by ToshihikoMakita** [comment]
Please refer to my test result in test-authoed-as-block-patched.pdf in out/pdf5.ml folder.

[2020-01-16-scall-down-to-fit.zip](https://github.com/AntennaHouse/pdf5-ml/files/4074466/2020-01-16-scall-down-to-fit.zip)

Even if I patched inline fo:externalgrpahic/graphic/@contentwidth="
scale-down-to-fit", @content-height="scale-down-to-fit", scaling="uniform", we cannot get the desired (fitted) result. So I think the only solution for this is to specify image/@placement="break".

![patched-result](https://user-images.githubusercontent.com/1801890/72575279-3681f280-390f-11ea-979c-2df30031914a.png)

**Comment by steinbacher01** [comment]
OK. Thanks for the response.
