### ISSUE TITLE
Use if:set and if:true in Ant build.xml

### ISSUE THREAD

**Issue by tgraham-antenna** [AntennaHouse/pdf5-ml#18]
The current `build.xml` has multiple variations of an `<exec>` task for running `AHFCmd`.  It also has multiple `<condition>` that set properties that are used to work out which `<exec>` to use.

Since Ant 1.9.1 (released in May 2013), Ant has supported its 'if' and 'unless' attributes on any task or element.  See https://ant.apache.org/manual-1.9.x/ifunless.html.

It seems to me that if it is okay for the build file to only work with Ant 1.9.1 or later, then the build file could be simplified by adding 'if' and 'unless' attributes to a single `<exec>` that handles all the variations.

An excerpt from a build file that I use is below.  Hopefully it demonstrates what I mean.

````
    <arg value="-2pass" if:true="${2pass}" />
    <arg value="-lpdf" if:true="${linearize}" />
    <arg value="-pdfver" />
    <arg value="${pdfver}" />
    <arg value="-i" if:set="ahfsettings" />
    <arg value="${ahfsettings}" if:set="ahfsettings" />
````

Of course, if you cannot expect Ant 1.9.1 or later, then you cannot use this technique.

**Comment by ToshihikoMakita** [comment]
@if:true seems to be very convenient. But at this time we must support old DITA-OT such as 1.8.5 because there are users who want to use DITA 1.2 rather than 1.3 or other reasons. DITA-OT 1.8.5 bundles old Ant 1.8.4. If we force users to replaces [DITA-OT]/tools/ant/ to Ant 1.9.1 it will works fine. But it may not  practical.

![ant185](https://cloud.githubusercontent.com/assets/1801890/24693706/c6ce8eec-1a19-11e7-929d-f678930e58df.png)

**Comment by tgraham-antenna** [comment]
That's too bad.  I had hoped that an Ant from 2013 would be old enough, but it isn't.

Feel free to close this issue.
