### ISSUE TITLE
Foot note issue

### ISSUE THREAD

**Issue by hemantverma25** [AntennaHouse/pdf5-ml#195]
When we integrate latest PDF5 ml plugin with DITA-OT-3.5.4 and print foot note in table then it is coming twice earlier it was working fine. Please suggest

**Comment by ToshihikoMakita** [comment]
Could you attach the minimum sample DITA instance?

**Comment by hemantverma25** [comment]
We have shared FO file in separate mail

**Comment by ToshihikoMakita** [comment]
Unfortunately you are requesting us to analyze the difficulty produced with your heavy customized plug-in code. This is not suitable with this issue list. If your difficulty is reproduced with pure (non-customized) PDF5-ML plug-in, please send us the sample minimum DITA instance. Otherwise this kind of support should be done with support contract with you and Antenna House, Inc.

**Comment by ToshihikoMakita** [comment]
Check your customization code by yourself! 

    <xsl:template match="*[contains(@class, ' topic/table ')]" name="processTable">

This code outputs footnotes after calling original PDF5-ML `tgroup` template:

    <xsl:apply-templates select="*[contains(@class, ' topic/tgroup ')]">
     ...
    <xsl:if test="not($pDisplayFnAtEndOfTopic)">
        <xsl:call-template name="makeFootNote">
            <xsl:with-param name="prmElement" select="."/>
        </xsl:call-template>
    </xsl:if>
    
 Original PDF5-ML `tgroup` template also outputs footnotes after processing `tgroup`.

https://github.com/AntennaHouse/pdf5-ml/blob/master/com.antennahouse.pdf5.ml/xsl/dita2fo_tableelements.xsl line 385.

This is the cause.
