### ISSUE TITLE
Table footnotes within thead not displayed in output

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#197]
Table footnotes within the thead element are not displayed in the output. The footnote content is displayed as expected below the table, but the reference # and link are missing from the tablehead entries.

![table-thead-fn](https://user-images.githubusercontent.com/36418458/109198061-62eb7d80-7763-11eb-8a3b-ae8adf5170b0.png)

![TableFN](https://user-images.githubusercontent.com/36418458/109198074-65e66e00-7763-11eb-80be-59982c40abcd.png)

I tested this on the base PDF5.ml plugin with the same result. 

I can attach a sample if needed. 

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
> I can attach a sample if needed.

Thank you, please attach the minimum test data.

**Comment by steinbacher01** [comment]
[table-fn-sample.zip](https://github.com/AntennaHouse/pdf5-ml/files/6049850/table-fn-sample.zip)

A different writer reported that this works in their table. This is probably related to the morerows attribute in the thead row entry.

**Comment by ToshihikoMakita** [comment]
Thank you. I will try it as soon as possible.

**Comment by ToshihikoMakita** [comment]
I found the cause. In DITA authoring, `fn` with `@id` must be referenced with `xref`. Otherwise the footnote reference character (*N) will not appeared. I attached revised authoring:

[r_crated_uncrated_Myo_weight_measuremnt_clearance.zip](https://github.com/AntennaHouse/pdf5-ml/files/6050044/r_crated_uncrated_Myo_weight_measuremnt_clearance.zip)

The revised result is as follows:

![fn_New](https://user-images.githubusercontent.com/1801890/109309129-3b410600-7886-11eb-9955-366a975c9665.png)

3.2.2.16 <fn>
http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/base/fn.html#fn

_A footnote that specifies an @id attribute is a use-by-reference footnote. Upon output, it does not appear anywhere unless it has been referenced using an <xref> with the @type attribute set to "fn"._

Hope this helps your understanding.

**Comment by steinbacher01** [comment]
Thanks for quick response. I made the change you suggested and it is now working as exptected.
