### ISSUE TITLE
ja strings for xref page

### ISSUE THREAD

**Issue by steinbacher01** [AntennaHouse/pdf5-ml#209]
Our localization team has pointed out that Japanese PDFs use "p." for xrefs that point to a specific page. 

![ja-xref-step](https://user-images.githubusercontent.com/36418458/125104267-ccc94b80-e0a2-11eb-873b-78d9218380c1.jpg)

Is this acceptable for Japanese translations, or is there a more preferred string that we should use?

com.antennahouse.pdf5.ml\config\ja_style.xml

`
<variable name="Xref_Prefix_Title_Page"> (p.</variable>
`
`
<variable name="Xref_Prefix_Page_Only"> p.</variable>
`

We've also had some questions about the use of bold for titles. Is there a preferred convention for font weight in regards to Japanese characters within titles?

Thanks, 

Leroy Steinbacher

**Comment by ToshihikoMakita** [comment]
Yes, it is acceptable for Japanese. Another choices are "7ページ" or "7頁". But "p.7" is most concise for technical documents. In addition, it may be desirable to use full width "（" and "）" to enclose page references. (Consult your Japanese distributor for final decision)

 `font-weight="bold"` or `"font-style="italic"` is not used in Japanese formatting. They are applicable only for Latin sentences in Japanese document. However if you use Microsoft Word,  `font-weight="bold"` or `"font-style="italic"` will be functional even when there is no actual relevant Japanese font in operating environment this is because Microsoft Word renders glyphs simulating bold or italic.

General Japanese formatting rules are:

- Do not use italic (There is no italic font for Japanese character)
- If you want to use bolder fonts to titles or emphasized words, select bolder font families in the same vendor in serif or sans-serif category.

Here is sample Japanese font families from Morisawa.

[https://www.morisawa.co.jp/fonts/specimen/1477](https://www.morisawa.co.jp/fonts/specimen/1477)

![2021-07-10-3_New](https://user-images.githubusercontent.com/1801890/125155755-eb137200-e19c-11eb-9fe4-1ae07f64866e.png)

**Comment by steinbacher01** [comment]
Thank you very much for the information.

**Comment by ToshihikoMakita** [comment]
For your reference, AH Formatter has the function that simulates font-family including each font that have different font-family name.

[https://www.antenna.co.jp/AHF/help/en/ahf-font.html#font-configration-file](https://www.antenna.co.jp/AHF/help/en/ahf-font.html#font-configration-file)

This is useful because you can simulate font-weight="bold" to Japanese fonts without changing font-family name.

Hope this helps your development.
